networks:
  metacrawlable-network:
    driver: bridge

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - metacrawlable-network
    container_name: metacrawlable-app

  # テスト実行用サービス
  playwright-test:
    build:
      context: .
      target: test
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./tests:/app/tests
    working_dir: /app
    environment:
      - CI=true
      - PLAYWRIGHT_WORKERS=4
      - BASE_URL=http://metacrawlable-app:3000
    networks:
      - metacrawlable-network