networks:
  metacrawlable-network:
    driver: bridge

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - metacrawlable-network
    container_name: metacrawlable-app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s
    mem_limit: 1g
    cpus: 1.0

  # テスト実行用サービス
  playwright-test:
    build:
      context: .
      target: test
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./tests:/app/tests
    working_dir: /app
    environment:
      - CI=true
      - PLAYWRIGHT_WORKERS=1  # パフォーマンス改善のため並列数を削減
      - BASE_URL=http://metacrawlable-app:3000
    networks:
      - metacrawlable-network
    mem_limit: 3g
    shm_size: 2g
    cpus: 2.0