services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # テスト実行用サービス
  playwright-test:
    build:
      context: .
      target: test
    depends_on:
      - app
    volumes:
      - ./tests:/app/tests
    working_dir: /app
    environment:
      - CI=true
      - PLAYWRIGHT_WORKERS=4
      - BASE_URL=http://app:3000