services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEV_HOST=localhost
      - DEV_PORT=3000

  # テスト実行用サービス
  playwright-test:
    build:
      context: .
      target: test
    depends_on:
      - app
    network_mode: "host"
    volumes:
      - ./tests:/app/tests
    working_dir: /app
    environment:
      - CI=true
      - PLAYWRIGHT_WORKERS=4
      - DEV_HOST=localhost
      - DEV_PORT=3000